language: php

sudo: required
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGO_REPO_URI="http://repo.mongodb.com/apt/ubuntu"
    - MONGO_REPO_TYPE="precise/mongodb-enterprise/"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb.list"
  matrix:
    - DRIVER_VERSION=1.2.0 SERVER_VERSION=2.6
    - DRIVER_VERSION=1.2.0 SERVER_VERSION=3.0
    - DRIVER_VERSION=1.2.0 SERVER_VERSION=3.2

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: DRIVER_VERSION=devel SERVER_VERSION=3.6
    - php: 7.4
      env: DRIVER_VERSION=1.4.2 SERVER_VERSION=3.2
    - php: 7.3
      env: DRIVER_VERSION=devel SERVER_VERSION=3.6
    - php: 7.3
      env: DRIVER_VERSION=1.4.2 SERVER_VERSION=3.2
    - php: 7.2
      env: DRIVER_VERSION=devel SERVER_VERSION=3.6
    - php: 7.2
      env: DRIVER_VERSION=1.4.2 SERVER_VERSION=3.2
    - php: 7.0
      env: DRIVER_VERSION=1.3.0 SERVER_VERSION=2.6
    - php: 7.0
      env: DRIVER_VERSION=1.3.0 SERVER_VERSION=3.2
    - php: 7.0
      env: DRIVER_VERSION=1.4.0 SERVER_VERSION=3.2
    - php: 7.0
      env: DRIVER_VERSION=devel SERVER_VERSION=3.2
    - php: 7.0
      env: DRIVER_VERSION=devel SERVER_VERSION=3.4
    - php: 7.0
      env: DRIVER_VERSION=devel SERVER_VERSION=3.6

before_install:
  - ./.travis.sh

script:
  - /tmp/phpunit tests
