language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12

env:
  global:
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGO_REPO_URI="http://repo.mongodb.com/apt/ubuntu"
    - MONGO_REPO_TYPE="precise/mongodb-enterprise/"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb.list"
  matrix:
    - DRIVER_VERSION=1.2.0 SERVER_VERSION=2.6
    - DRIVER_VERSION=1.2.0 SERVER_VERSION=3.0
    - DRIVER_VERSION=1.2.0 SERVER_VERSION=3.2

matrix:
  fast_finish: true
  include:
    - php: hhvm-3.3
      env: IS_HHVM=1

    - php: hhvm-3.6
      env: IS_HHVM=1

    - php: hhvm-3.9
      env: IS_HHVM=1

    - php: hhvm-3.12
      env: IS_HHVM=1

    - php: 7.0
      env: DRIVER_VERSION=1.2.0 SERVER_VERSION=2.4
    - php: 7.0
      env: DRIVER_VERSION=devel SERVER_VERSION=3.2
  exclude:
    - php: 5.4
      env: DRIVER_VERSION=stable SERVER_VERSION=2.6
    - php: 5.4
      env: DRIVER_VERSION=stable SERVER_VERSION=3.0
    - php: 5.5
      env: DRIVER_VERSION=stable SERVER_VERSION=2.6
    - php: 5.5
      env: DRIVER_VERSION=stable SERVER_VERSION=3.0

before_install:
  - sudo ./.travis.sh

script:
  - phpunit tests
